### ISSUE TITLE
Refactor: Returning errors

### ISSUE THREAD

**Issue by cristianoliveira** [rust-on-slack/rust-slack-inviter#1]
Today we do the ugliest thing on earth to return the message as `json`. You can see here: https://github.com/rust-on-slack/rust-slack-inviter/blob/master/src/main.rs#L49

Would be nice to create a proper `struct` fill it and then parse it as` json`.

**Comment by Redrield** [comment]
I've got a PR lined up for this, I'll submit it as the clock strikes midnight so that it counts towards Hacktoberfest :)
